version: '3.2'

services:

  proxy:
    ports:
      - "80:80"
      - "443:443"

  nginx:
    depends_on:
      - proxy
      - varnish

  ckan:
    depends_on:
      - datapusher
    links:
      - datapusher
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    build:
      context: ckan
      args:
        # Comment me out if working with Chinese server
        # PIP_INDEX_URL: https://pypi.tuna.tsinghua.edu.cn/simple
        GITHUB_URL: https://github.com.cnpmjs.org
        CKAN_BRANCH: ckan-2.7.3
        EXTRA_FILESYSTEM: "./overrides/vital-strategies/filesystem/"
        PRE_INSTALL: "sed  -i -e 's/psycopg2==2.4.5/psycopg2==2.7.7/g' ~/venv/src/ckan/requirements.txt"
        POST_INSTALL: |
          install_standard_ckan_extension_github -r ViderumGlobal/ckanext-querytool -b v1.9.4 &&\
          install_standard_ckan_extension_github -r ckan/ckanext-geoview && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l en -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l es -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l fr -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l pt_BR -f && \
          cd ~/venv/src/ckanext-querytool && ~/venv/bin/python setup.py compile_catalog -l zh_CN -f
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-shandong-theme-

  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-vital-strategies-theme
    build:
      context: ckan
      args:
        CKAN_BRANCH: ckan-2.7.3
        POST_INSTALL: |
          install_standard_ckan_extension_github -r keitaroinc/ckanext-s3filestore &&\
          install_standard_ckan_extension_github -r ViderumGlobal/ckanext-querytool &&\
          install_standard_ckan_extension_github -r ckan/ckanext-geoview
    environment:
      - CKAN_CONFIG_TEMPLATE_PREFIX=vital-strategies-shandong-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        APK_REPOSITORY: https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.6/community/
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"

  datapusher:
    container_name: datapusher
    build:
      context: datapusher/
      args:
        APK_REPOSITORY: https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.6/community/
